version: 2

jobs:
  test:
    working_directory: ~/cook

    docker:
      - image: node:8

    steps:
      - checkout

      - restore_cache:
          keys:
            - cook-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - cook-{{ .Branch }}
            - cook-master-{{ checksum "yarn.lock" }}
            - cook-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          key: cook-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn
            - ~/cook/node_modules

  deploy:
    working_directory: ~/cook

    docker:
      - image: node:8

    steps:
      - checkout

      - restore_cache:
          keys:
            - deploy-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "functions/yarn.lock" }}
            - deploy-{{ .Branch }}
            - deploy-master-{{ checksum "yarn.lock" }}-{{ checksum "functions/yarn.lock" }}
            - deploy-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Install functions dependencies
          command: cd functions && yarn

      - run:
          name: Build
          command: yarn build

      - deploy:
          name: Deploy
          command: yarn deploy --token "$FIREBASE_TOKEN"

      - save_cache:
          key: deploy-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "functions/yarn.lock" }}
          paths:
            - ~/.yarn
            - ~/cook/node_modules
            - ~/cook/functions/node_modules

workflows:
  version: 2
  stack:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
