version: 2.1

jobs:
  test:
    working_directory: ~/cook

    docker:
      - image: node:12

    steps:
      - checkout

      - restore_cache:
          keys:
            - cook-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - cook-{{ .Branch }}
            - cook-master-{{ checksum "yarn.lock" }}
            - cook-master

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          key: cook-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn
            - ~/cook/node_modules

workflows:
  version: 2
  stack:
    jobs:
      - test
