// export { default as BannerPage } from './BannerPage'
// export { default as BlankPage } from './BlankPage'
export { default as DetailPage } from './DetailPage'
export { default as FormPage } from './FormPage'
// export { default as Page } from './Page'
export { default as TitlePage } from './TitlePage'
export { default as WithNavbar } from './WithNavbar'
